# Generated by Django 6.1.1 on 2026-09-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='geo_approx',
            field=models.BooleanField(default=False),
        ),
    ]
